### ISSUE TITLE
Infografia_Rigoberto_Suridai

### ISSUE THREAD

**Issue by DuilioAquino10** [Near-University-Tec-de-Tlaxiaco/iHome#2]

**Comment by kirus21** [comment]
[Infografia Sprint4.pdf](https://github.com/Near-University-Tec-de-Tlaxiaco/iHome/files/8884234/Infografia.Sprint4.pdf)

**Comment by josealfredo79** [comment]
Falta la calificacion

**Comment by Brisa-4** [comment]
Calificación: 18.5/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
