### ISSUE TITLE
Infografia_Christopheremv

### ISSUE THREAD

**Issue by DuilioAquino10** [Near-University-Tec-de-Tlaxiaco/iHome#3]

**Comment by christopheremv** [comment]
[Infografía calidad de software.pdf](https://github.com/Near-University-Tec-de-Tlaxiaco/iHome/files/8903012/Infografia.calidad.de.software.pdf)

**Comment by Brisa-4** [comment]
Bien hecho
Calificacion: 20%

**Comment by josealfredo79** [comment]
La infografía se subio despues de la fecha límite...

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
