### ISSUE TITLE
Practica pruebas unitarias

### ISSUE THREAD

**Issue by DuilioAquino10** [Near-University-Tec-de-Tlaxiaco/iHome#6]

**Comment by DuilioAquino10** [comment]
[Reporte.pdf](https://github.com/Near-University-Tec-de-Tlaxiaco/iHome/files/8912244/Reporte.pdf)

**Comment by Yabin-2021** [comment]
Calificación 20/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
